package de.agb.blutspende_app.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904B3D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD3)
val onPrimaryContainerLight = Color(0xFF3A0A03)
val secondaryLight = Color(0xFF775750)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD3)
val onSecondaryContainerLight = Color(0xFF2C1510)
val tertiaryLight = Color(0xFF8F4C34)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDBCF)
val onTertiaryContainerLight = Color(0xFF390C00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF231917)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF231917)
val surfaceVariantLight = Color(0xFFF5DDD9)
val onSurfaceVariantLight = Color(0xFF534340)
val outlineLight = Color(0xFF85736F)
val outlineVariantLight = Color(0xFFD8C2BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2C)
val inverseOnSurfaceLight = Color(0xFFFFEDE9)
val inversePrimaryLight = Color(0xFFFFB4A5)



val primaryDark = Color(0xFFFFB4A5)
val onPrimaryDark = Color(0xFF561F13)
val primaryContainerDark = Color(0xFF733427)
val onPrimaryContainerDark = Color(0xFFFFDAD3)
val secondaryDark = Color(0xFFE7BDB4)
val onSecondaryDark = Color(0xFF442A24)
val secondaryContainerDark = Color(0xFF5D3F39)
val onSecondaryContainerDark = Color(0xFFFFDAD3)
val tertiaryDark = Color(0xFFFFB59C)
val onTertiaryDark = Color(0xFF55200B)
val tertiaryContainerDark = Color(0xFF72351F)
val onTertiaryContainerDark = Color(0xFFFFDBCF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A110F)
val onBackgroundDark = Color(0xFFF1DFDB)
val surfaceDark = Color(0xFF1A110F)
val onSurfaceDark = Color(0xFFF1DFDB)
val surfaceVariantDark = Color(0xFF534340)
val onSurfaceVariantDark = Color(0xFFD8C2BD)
val outlineDark = Color(0xFFA08C88)
val outlineVariantDark = Color(0xFF534340)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DFDB)
val inverseOnSurfaceDark = Color(0xFF392E2C)
val inversePrimaryDark = Color(0xFF904B3D)






